# Generated by Django 6.0.6 on 2026-07-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activeinvestment_status_referral_referrer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('eth_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('usdt_erc20_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('usdt_trc20_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
