# Generated by Django 6.0.6 on 2026-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('account', 'Account'), ('investment', 'Investment'), ('security', 'Security'), ('withdrawal', 'Withdrawal')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
