# Generated by Django 6.0.6 on 2026-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_supportarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
