# Generated by Django 6.0.6 on 2026-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinvestment',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activeinvestment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
