# Generated by Django 6.0.6 on 2026-07-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_activeinvestment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinvestment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activeinvestment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
