# Generated by Django 6.0.6 on 2026-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_btc_address_userprofile_btc_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usdt_erc20_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usdt_trc20_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
