# Generated by Django 6.0.6 on 2026-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_usdt_erc20_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvestment',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
