# Generated by Django 6.0.6 on 2026-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='btc_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='eth_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
