# Generated by Django 6.0.6 on 2026-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofile_bonus_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='btc_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qrcodes/'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='eth_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qrcodes/'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='usdt_erc20_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qrcodes/'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='usdt_trc20_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qrcodes/'),
        ),
    ]
