# Generated by Django 6.0.6 on 2026-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_companywallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
