# Generated by Django 6.0.6 on 2026-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_withdrawal_currency_withdrawal_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usdt_erc20_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usdt_trc20_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
