# Generated by Django 6.0.6 on 2026-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_userprofile_usdt_erc20_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT_ERC20', 'USDT ERC20'), ('USDT_TRC20', 'USDT TRC20')], default='BTC', max_length=20),
            preserve_default=False,
        ),
    ]
