# Generated by Django 6.0.6 on 2026-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_deposit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvestment',
            name='currency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT_ERC20', 'USDT ERC20'), ('USDT_TRC20', 'USDT TRC20'), ('USD', 'USD')], default='USD', max_length=20),
        ),
    ]
