# Generated by Django 6.0.6 on 2026-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_referralcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='bonus_paid',
            field=models.BooleanField(default=False),
        ),
    ]
