# Generated by Django 6.0.6 on 2026-07-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_deposit_bonus_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='count',
        ),
    ]
