# Generated by Django 6.0.6 on 2026-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userprofile_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('payout', 'Payout'), ('bonus', 'Bonus'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=20),
        ),
    ]
