# Generated by Django 6.0.6 on 2026-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_withdrawal_options_withdrawal_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvestment',
            name='last_payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeinvestment',
            name='payouts_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activeinvestment',
            name='principal_returned',
            field=models.BooleanField(default=False),
        ),
    ]
