# Generated by Django 6.0.6 on 2026-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_activeinvestment_last_payout_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvestment',
            name='payout_type',
            field=models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily')], default='once', max_length=10),
        ),
    ]
