# Generated by Django 6.0.6 on 2026-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet', models.CharField(blank=True, max_length=200, null=True)),
                ('btc_qr', models.ImageField(blank=True, null=True, upload_to='company_wallets/')),
                ('eth_wallet', models.CharField(blank=True, max_length=200, null=True)),
                ('eth_qr', models.ImageField(blank=True, null=True, upload_to='company_wallets/')),
                ('usdt_erc20_wallet', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_erc20_qr', models.ImageField(blank=True, null=True, upload_to='company_wallets/')),
                ('usdt_trc20_wallet', models.CharField(blank=True, max_length=200, null=True)),
                ('usdt_trc20_qr', models.ImageField(blank=True, null=True, upload_to='company_wallets/')),
            ],
        ),
    ]
