# Generated by Django 6.0.6 on 2026-07-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crypto.navigationlink'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
