# Generated by Django 6.0.6 on 2026-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_navigationlink_parent_alter_navigationlink_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Accessible for Everyone', max_length=200)),
                ('subtitle', models.CharField(default='Crypto development accessible', max_length=200)),
            ],
            options={
                'verbose_name': 'Accessible Section',
                'verbose_name_plural': 'Accessible Sections',
            },
        ),
    ]
