# Generated by Django 6.0.6 on 2026-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_accessiblesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlanSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
