# Generated by Django 6.0.6 on 2026-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_investmentplanslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplanslide',
            name='button_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
