# Generated by Django 6.0.6 on 2026-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_investmentplancard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='WE ARE Bitnet', max_length=200)),
                ('intro_text', models.TextField()),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('advantages_text', models.TextField(blank=True, null=True)),
                ('guarantees_text', models.TextField(blank=True, null=True)),
                ('extra_text', models.TextField(blank=True, null=True)),
                ('read_more_url', models.URLField(default='/features')),
            ],
        ),
    ]
