# Generated by Django 6.0.6 on 2026-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_alter_aboutus_options_alter_aboutus_read_more_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSaleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(default='Accessible for Everyone', max_length=200)),
                ('left_subtitle', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Sign Up', max_length=50)),
                ('button_url', models.CharField(default='/register', max_length=200)),
                ('right_title', models.CharField(default='The trading platform for the future', max_length=200)),
                ('end_date', models.DateTimeField()),
                ('contribution_received', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('min_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Token Sale Section',
                'verbose_name_plural': 'Token Sale Sections',
            },
        ),
    ]
