# Generated by Django 6.0.6 on 2026-07-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_tokensalesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(help_text='H4 text styled yellow on black background', max_length=200)),
                ('main_title', models.CharField(help_text='H1 text, fifth word styled ash', max_length=200)),
                ('canvas_text', models.CharField(blank=True, help_text='Optional text for the swinging canvas', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SwingContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content inside the container')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='crypto.swingsection')),
            ],
        ),
    ]
