# Generated by Django 6.0.6 on 2026-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_swingsection_swingcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='swingcontainer',
            name='title',
            field=models.CharField(default='Swing Container', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swingcontainer',
            name='content',
            field=models.TextField(),
        ),
    ]
