# Generated by Django 6.0.6 on 2026-07-06 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_swingcontainer_title_alter_swingcontainer_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='exchange/')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exchange/icons/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='crypto.exchangesection')),
            ],
        ),
    ]
