# Generated by Django 6.0.6 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_exchangesection_exchangeicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage_text', models.CharField(max_length=100)),
                ('duration_text', models.CharField(max_length=100)),
                ('grey_title', models.CharField(max_length=100)),
                ('white_title', models.CharField(max_length=100)),
                ('left_header', models.CharField(max_length=100)),
                ('right_header', models.CharField(max_length=100)),
                ('button_text', models.CharField(default='Sign Up', max_length=50)),
                ('button_url', models.URLField(default='/register/')),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
            },
        ),
    ]
