# Generated by Django 6.0.6 on 2026-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_investmentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='button_url',
            field=models.CharField(default='/register/'),
        ),
    ]
