# Generated by Django 6.0.6 on 2026-07-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_alter_investmentplan_button_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='grey_title',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='left_header',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='right_header',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='white_title',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='maturity_text',
            field=models.CharField(default='CAPITAL IS RETURNED ON MATURITY', max_length=200),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='button_url',
            field=models.CharField(default='/register/', max_length=200),
        ),
    ]
