# Generated by Django 6.0.6 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_remove_investmentplan_grey_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(default='BITCOIN', max_length=50)),
                ('title_second', models.CharField(default='CALCULATOR', max_length=50)),
                ('subtitle', models.CharField(default='Find out the current Bitcoin value with our easy-to-use converter.', max_length=200)),
                ('default_currency', models.CharField(default='ARS', max_length=10)),
            ],
        ),
    ]
