# Generated by Django 6.0.6 on 2026-07-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0019_currencyrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
