# Generated by Django 6.0.6 on 2026-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0020_delete_currencyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinstrument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='marketinstrument',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marketinstrument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='marketinstrument',
            name='value',
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='ask',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='bid',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='high',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='low',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='technical_rating',
            field=models.CharField(default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='marketinstrument',
            name='ticker',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='change_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='change_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
