# Generated by Django 6.0.6 on 2026-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0022_marketsidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinstrument',
            name='ask',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='change_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketinstrument',
            name='technical_rating',
            field=models.CharField(blank=True, default='Neutral', max_length=20, null=True),
        ),
    ]
