# Generated by Django 6.0.6 on 2026-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0023_alter_marketinstrument_ask_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketSidebar',
        ),
        migrations.AlterModelOptions(
            name='investmentplanslide',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='maturity_text',
            field=models.CharField(default='Capital is returned on maturity', max_length=200),
        ),
    ]
