# Generated by Django 6.0.6 on 2026-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0024_delete_marketsidebar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplanslide',
            options={'ordering': ['order'], 'verbose_name': 'Investment Plan Slide', 'verbose_name_plural': 'Investment Plan Slides'},
        ),
        migrations.RemoveField(
            model_name='investmentplanslide',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='investmentplanslide',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='investmentplanslide',
            name='button_text',
            field=models.CharField(default='Sign Up', max_length=50),
        ),
    ]
