# Generated by Django 6.0.6 on 2026-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0025_alter_investmentplanslide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='button_url',
            field=models.CharField(default='/signup/', max_length=200),
        ),
    ]
