# Generated by Django 6.0.6 on 2026-07-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0027_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
