# Generated by Django 6.0.6 on 2026-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0030_investmentplan_duration_hours_alter_aboutus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
